In [3]:
my_list = [1,2,3]

In [1]:
import numpy as np

In [2]:
arr = np.array

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,11,2) # the third parameter is step

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(2)

array([1., 1.])

In [24]:
np.linspace(0,5,10) # the third argument is the number of points you want

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
np.random.rand()

0.8705889087816929

In [28]:
np.random.rand(7)

array([0.30248653, 0.93399528, 0.4852351 , 0.2577772 , 0.19705331,
       0.78365736, 0.24370292])

In [29]:
np.random.rand(3,3)

array([[0.52917075, 0.00520366, 0.12493499],
       [0.86218353, 0.73328731, 0.48534365],
       [0.0758356 , 0.85489596, 0.89967573]])

In [30]:
np.random.randn(2)

array([0.09771888, 0.42436503])