In [2]:
my_list = [1,2,3]

In [6]:
import numpy as np

In [2]:
arr = np.array

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [44]:
arr+2

array([  2, 102, 102, 102, 102,   7,   8,   9,  10,  11,  12])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,11,2) # the third parameter is step

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(2)

array([1., 1.])

In [24]:
np.linspace(0,5,10) # the third argument is the number of points you want

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
np.random.rand()

0.8705889087816929

In [28]:
np.random.rand(7)

array([0.30248653, 0.93399528, 0.4852351 , 0.2577772 , 0.19705331,
       0.78365736, 0.24370292])

In [29]:
np.random.rand(3,3)

array([[0.52917075, 0.00520366, 0.12493499],
       [0.86218353, 0.73328731, 0.48534365],
       [0.0758356 , 0.85489596, 0.89967573]])

In [30]:
np.random.randn(2)

array([0.09771888, 0.42436503])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr[10]

10

In [18]:
arr[1:5]

array([1, 2, 3, 4])

In [19]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [20]:
arr[1:5]=100

In [21]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
#comma notation for matrix

In [28]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
arr_2d[2,1]

8

In [30]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [38]:
arr_random_2d = np.random.rand(10,10)

In [40]:
arr_random_2d

array([[0.92396888, 0.41303857, 0.42567313, 0.64123148, 0.77350584,
        0.02683048, 0.80131969, 0.48925917, 0.31269031, 0.30762698],
       [0.63646462, 0.43759921, 0.77905866, 0.54152734, 0.97448392,
        0.80688452, 0.57255611, 0.25086282, 0.78228392, 0.70806508],
       [0.9570095 , 0.4411646 , 0.91775168, 0.28028839, 0.13347082,
        0.23657513, 0.64092608, 0.63705488, 0.54317107, 0.67054578],
       [0.42560184, 0.25915041, 0.90966034, 0.62978315, 0.39651454,
        0.29830272, 0.86877301, 0.39218765, 0.8564816 , 0.97627128],
       [0.67816605, 0.9626094 , 0.79750363, 0.30089007, 0.28635712,
        0.62727432, 0.05674686, 0.60645496, 0.22678378, 0.74365425],
       [0.93149293, 0.78180115, 0.36578631, 0.05102004, 0.09251219,
        0.16853465, 0.02677061, 0.15395473, 0.99663016, 0.24070263],
       [0.80572918, 0.67596527, 0.0191587 , 0.71782262, 0.88438143,
        0.9135476 , 0.44134137, 0.03514706, 0.9084455 , 0.0548622 ],
       [0.26745263, 0.06518592, 0.4360062

In [39]:
arr_random_2d[2:,5:]

array([[0.23657513, 0.64092608, 0.63705488, 0.54317107, 0.67054578],
       [0.29830272, 0.86877301, 0.39218765, 0.8564816 , 0.97627128],
       [0.62727432, 0.05674686, 0.60645496, 0.22678378, 0.74365425],
       [0.16853465, 0.02677061, 0.15395473, 0.99663016, 0.24070263],
       [0.9135476 , 0.44134137, 0.03514706, 0.9084455 , 0.0548622 ],
       [0.68776496, 0.6831409 , 0.55135252, 0.66782818, 0.49974527],
       [0.85917014, 0.10371225, 0.26269557, 0.35876358, 0.12421823],
       [0.32952953, 0.53719263, 0.20302022, 0.89672679, 0.37126245]])

In [41]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [42]:
arr[arr>6]

array([100, 100, 100, 100,   7,   8,   9,  10])

In [43]:
arr>5

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [46]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr * 2

array([  0, 200, 200, 200, 200,  10,  12,  14,  16,  18,  20])

In [48]:
np.sqrt(arr)

array([ 0.        , 10.        , 10.        , 10.        , 10.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [49]:
np.exp(arr)

array([1.00000000e+00, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43,
       2.68811714e+43, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [50]:
np.max(arr)

100

In [51]:
np.sin(arr)

array([ 0.        , -0.50636564, -0.50636564, -0.50636564, -0.50636564,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [52]:
np.log(arr)

/Users/chenyunzhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 4.60517019, 4.60517019, 4.60517019, 4.60517019,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])